# Generated by Django 2.0 on 2019-07-27 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('for_people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerPolyclinic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Ответ о поликлиннике',
                'verbose_name_plural': 'Ответы о поликлинниках',
            },
        ),
        migrations.CreateModel(
            name='AnswerSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Ответ по персоналу',
                'verbose_name_plural': 'Ответы по персоналу',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=40, verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='Polyclinic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=40, verbose_name='Поликлинника')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polyclinic_city', to='for_people.City', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Поликлинника',
                'verbose_name_plural': 'Поликлинники',
            },
        ),
        migrations.CreateModel(
            name='QuestionPolyclinic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(default='', max_length=1000, verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Вопрос о поликлиннике',
                'verbose_name_plural': 'Воспросы о поликлиннике',
            },
        ),
        migrations.CreateModel(
            name='QuestionSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(default='', max_length=1000, verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Вопрос по персоналу',
                'verbose_name_plural': 'Воспросы по персоналу',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=40, verbose_name='ФИО')),
                ('position', models.CharField(default='', max_length=40, verbose_name='Дожность')),
                ('polyclinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_polyclinic', to='for_people.Polyclinic', verbose_name='Поликлинника')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователь',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Номер талона')),
                ('is_passed', models.BooleanField(default=False, verbose_name='Пройден')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_subject', to='for_people.Subject', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Номер талона',
                'verbose_name_plural': 'Номера талонов',
            },
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.AddField(
            model_name='answersubject',
            name='question_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_question_subject', to='for_people.QuestionSubject', verbose_name='Вопрос'),
        ),
        migrations.AddField(
            model_name='answersubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_subject', to='for_people.Subject', verbose_name='Поликлинника'),
        ),
        migrations.AddField(
            model_name='answerpolyclinic',
            name='polyclinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_polyclinic', to='for_people.Polyclinic', verbose_name='Поликлинника'),
        ),
        migrations.AddField(
            model_name='answerpolyclinic',
            name='question_polyclinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_question_polyclinic', to='for_people.QuestionPolyclinic', verbose_name='Вопрос'),
        ),
    ]
